-- Two things P1.5 needs in place before it's deployed.
--
-- 1. The staff bookings board reads each of today's bookings' messages
--    on every load, so `notifications` gets an index on `booking_id`
--    (generated by drizzle-kit from schema/bookings.ts).
CREATE INDEX "notifications_booking_id_idx" ON "notifications" USING btree ("booking_id");
--> statement-breakpoint
-- 2. Before P1.5 there was no check-in, so every session that has
--    already started is still `confirmed` — whether or not it happened.
--    The new no-show job marks any confirmed booking 15 minutes past its
--    start as `no_show`, so on its first run it would turn every one of
--    them into a "Missed" visit on the client's account and into the
--    no-show rate. Record them as `completed` instead (nothing tells a
--    real visit from a missed one, and completed is the answer that
--    doesn't blame the client), with an activity-log row for each so
--    "why is this completed?" has an answer. Run this migration right
--    before deploying: a session starting in between is still
--    `confirmed` when the job first runs.
WITH "backfilled" AS (
  UPDATE "bookings"
  SET "status" = 'completed', "updated_at" = now()
  WHERE "status" = 'confirmed' AND "start_at" < now()
  RETURNING "id"
)
INSERT INTO "activity_log" ("action", "entity_type", "entity_id", "before", "after", "reason")
SELECT
  'booking.completedAtCheckInCutover',
  'booking',
  "id"::text,
  '{"status":"confirmed"}',
  '{"status":"completed"}',
  'Took place before check-in existed (migration 0004); recorded as completed rather than a no-show'
FROM "backfilled";
